### ISSUE TITLE
issue with the autoaway config option

### ISSUE THREAD

**Issue by kcrpine** [blindelectron/ttServerManager#1]
am having a issue with the autoaway config option even though I set autoaway=False, if someone changes their status to away or it auto gets set from  the define auto away status after in the preffs of teamtalk it moves them to the root channel  even though  I told it autoaway to be false. I even tryed to set the autoawaychannel to a away channel and it still does root. not sure if this is a bug or I am doing something wrong.
Thanks
Kevin Roberts

**Comment by dragonwolfsp** [comment]
I will look in to this right now,, I am actively working on it at this exact moment.

**Comment by dragonwolfsp** [comment]
this issue is now fixed, if autoaway option is set to false, the auto away system will now properly deactivate.
