### ISSUE TITLE
Bug if the users away.

### ISSUE THREAD

**Issue by rexya2017** [blindelectron/ttServerManager#2]
Hi there,
I have seen a bug in the bot when the user is away then the bot will move to the specified channel. If the bot restarts and the user returns to Available, the bot will not move the user to the channel where they were previously.
Is it possible for a bot to remember that? my idea is that this can be added to the config file, like a system jail.

**Comment by dragonwolfsp** [comment]
While this could be added to the configuration file, it could cause a spam writing of the file if a user spams away than active. This is not currently within the scope of this project. As I would have to create a system that ensures that the file is not being written to, more than once at a time.

**Comment by dragonwolfsp** [comment]
I will be closing this issue do to the reasons listed above
